# Generated by Django 5.0.1 on 2024-02-26 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstaff',
            name='faculty_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='luanarapp.faculty', to_field='faculty_code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='luanarapp.faculty', to_field='faculty_code'),
        ),
    ]
