# Generated by Django 5.0.1 on 2024-02-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanarapp', '0002_alter_academicstaff_faculty_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='vacancies/'),
        ),
    ]
