# Generated by Django 5.0.1 on 2024-03-06 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanarapp', '0003_alter_vacancy_vacancy_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramNature',
            fields=[
                ('programnature_id', models.AutoField(primary_key=True, serialize=False)),
                ('programnature_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='campus_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='luanarapp.campus'),
        ),
        migrations.AddField(
            model_name='program',
            name='prospects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='programnature_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='luanarapp.programnature'),
        ),
        migrations.DeleteModel(
            name='Prospects',
        ),
    ]
