# Generated by Django 5.0.1 on 2024-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanarapp', '0009_remove_news_user_news_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='news',
            name='posted_by_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='posted_by_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
