# Generated by Django 5.0.1 on 2024-04-03 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanarapp', '0010_remove_news_posted_by_news_posted_by_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='posted_by_first_name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='posted_by_last_name',
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
