# Generated by Django 5.0.6 on 2024-06-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanarapp', '0014_alter_academicstaff_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstaff',
            name='staff_position',
            field=models.CharField(choices=[('Head of Faculty', 'Head of Faculty'), ('Deputy Head of Faculty', 'Deputy Head of Faculty'), ('Head of Department', 'Head of Department'), ('Lecturer', 'Lecturer'), ('Associate lecturer', 'Associate lecturer'), ('Part-Time Lecturer', 'Part Time Lecturer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='administrationstaff',
            name='staff_position',
            field=models.CharField(choices=[('Vice Chancellor', 'Vice chancellor'), ('Deputy Vice Chancellor', 'Deputy Vice Chancellor'), ('University Registrar', 'University Registrar'), ('Dean of Students Affairs', 'Dean of Students Affairs'), ('Human Resources Manager', 'Human Resources Manager')], max_length=100),
        ),
    ]
