# Generated by Django 5.0.6 on 2024-06-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanarapp', '0015_alter_academicstaff_staff_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='tag',
            field=models.CharField(blank=True, choices=[('Bunda', 'Bunda'), ('NRC', 'NRC'), ('CITY', 'CITY'), ('ODL', 'ODL'), ('LUANAR', 'LUANAR')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, choices=[('Bunda', 'Bunda'), ('NRC', 'NRC'), ('CITY', 'CITY'), ('ODL', 'ODL'), ('LUANAR', 'LUANAR')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo_description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(choices=[('Bunda', 'Bunda'), ('NRC', 'NRC'), ('CITY', 'CITY'), ('ODL', 'ODL'), ('LUANAR', 'LUANAR')], max_length=50),
        ),
    ]
