# Generated by Django 5.0.6 on 2024-06-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luanarapp', '0017_remove_announcement_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='tag',
            field=models.CharField(blank=True, choices=[('Bunda', 'Bunda'), ('NRC', 'NRC'), ('CITY', 'CITY'), ('ODL', 'ODL'), ('Public', 'Public')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, choices=[('Bunda', 'Bunda'), ('NRC', 'NRC'), ('CITY', 'CITY'), ('ODL', 'ODL'), ('Public', 'Public')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(choices=[('Bunda', 'Bunda'), ('NRC', 'NRC'), ('CITY', 'CITY'), ('ODL', 'ODL'), ('Public', 'Public')], max_length=50),
        ),
    ]
